openapi: 3.0.2
info:
  title: HIE-CM Profile Share
  version: '3.0'
servers:
  - url: https://dev.abdm.gov.in/hiecm/api
    description: Sandbox Server URL
  - url: https://live.abdm.gov.in/hiecm/api
    description: Production Server URL
components:
  parameters:
    callback_url:
      name: callback_url
      in: path
      explode: false
      required: true
      schema:
        type: string
    REQUEST_ID:
      name: REQUEST_ID
      in: header
      required: true
      description: Unique UUID for track the end to end request transaction
      schema:
        type: string
        format: uuid
        minimum: 1
        maximum: 100
        example: 18235d89-cb13-479d-ad71-7a57d5f669a8
      $ref: '#/components/parameters/REQUEST_ID'
    TIMESTAMP:
      name: TIMESTAMP
      in: header
      required: true
      description: >-
        Actual time of the request was initiated, ISO 8601 represents date and
        time by starting with the year, followed by the month, the day, the
        hour, the minutes, seconds and milliseconds
      schema:
        type: string
        format: date time
        minimum: 1
        maximum: 100
        example: '2022-10-06T15:10:00.587Z'
      $ref: '#/components/parameters/TIMESTAMP'
    Authorization:
      name: Authorization
      in: header
      required: true
      description: >-
        JWT Access token which was issued by ABDM session API after  successful
        validation of client id and secret
      schema:
        type: string
        format: bearer
        minimum: 1
        maximum: 200
        example: eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ2YXNhbnRoYWt1bWFyLmtlc2F2
      $ref: '#/components/parameters/Authorization'
    X_AUTH_TOKEN:
      name: X_AUTH_TOKEN
      in: header
      required: true
      description: >-
        JWT Authentication token which was issued by ABDM after successful
        validation of username and password
      schema:
        type: string
        format: bearer
        minimum: 1
        maximum: 100
        example: eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ2YXNhbnRoYWt1bWFyLmtlc2F2
      $ref: '#/components/parameters/X_AUTH_TOKEN'
    X_HIU_ID:
      name: X_HIU_ID
      in: header
      required: true
      description: >-
        Identifier of the health information user to which the request was
        intended
      schema:
        type: string
        format: string
        minimum: 1
        maximum: 100
        example: IN2810014366
      $ref: '#/components/parameters/X_HIU_ID'
    X_HIP_ID:
      name: X_HIP_ID
      in: header
      required: true
      description: >-
        Identifier of the health information provider to which the request was
        intended
      schema:
        type: string
        format: string
        minimum: 1
        maximum: 100
        example: IN2810014366
      $ref: '#/components/parameters/X_HIP_ID'
    X_CM_ID:
      name: X_CM_ID
      in: header
      required: true
      description: Suffix of the consent manager to which the request was intended
      schema:
        type: string
        format: string
        minimum: 1
        maximum: 100
        example: sbx
      $ref: '#/components/parameters/X_CM_ID'
paths:
  /v3/patient/profile/share:
    post:
      tags:
        - abdm-hiecm-profile-share
      operationId: abdm-profile-share 1
      summary: >-
        This API will be invoked from the integrator application for sharing the
        patient/user profile with the HMIS/LIMS.
      description: >-
        This is a API will be invoked from the <b>integrator application</b> to
        share the user/patient profile with HMIS/LIMS. <ol type='1'> <li>
        <b>Header</b>  <ol type='a'> <br/> <li>Authorization will be provided by
        the gateway session API after the successful verification of client ID
        and Secret [ Example:
        eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ2YXNhbnRoYWt1bWFyLmtlc2F2 ]</li>
        <li>REQUEST_ID unique UUID[ Example:
        18235d89-cb13-479d-ad71-7a57d5f669a8 ]</li> <li>TIMESTAMP  actual time
        of the requested was initiated[ Example: 2022-10-06T10:10:00.587 ]</li>
        <li>X_AUTH_TOKEN JWT Authentication token which was issued by ABDM after
        successful validation of username and password[ Example:
        eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ2YXNhbnRoYWt1bWFyLmtlc2F2 ]</li>
        <li>X_CM_ID  consent manager ID[ Example: ABDM_SBX ]</li> </ol> </li>
        <br/> <li> <b>Request Body</b> <ol type='a'><br/> <li>intent This is a
        key value pair  which contains the purpose [ Example: { hip_id:
        ABDM_HIP, context: 123, purpose: profile_share } ]</li> <li>metaData
        This is a key value pair which contains the location longitude and
        latitude[ Example: { lat: 20.5937 long: 78.9629} ]</li> </ol> </ol>
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/REQUEST_ID'
        - $ref: '#/components/parameters/TIMESTAMP'
        - $ref: '#/components/parameters/X_AUTH_TOKEN'
        - $ref: '#/components/parameters/X_CM_ID'
        - $ref: '#/components/parameters/X_HIU_ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - intent
              properties:
                intent:
                  type: object
                  nullable: false
                  required:
                    - hipId
                    - context
                    - purpose
                  properties:
                    hipId:
                      type: string
                      nullable: false
                      example: abdm_hip01
                    context:
                      type: number
                      nullable: false
                      example: 123
                    purpose:
                      type: string
                      nullable: false
                      enum:
                        - profile_share
                        - payment
                        - data_share
                      example: profile_share
                metaData:
                  type: object
                  nullable: true
                  required:
                    - lat
                    - long
                  properties:
                    lat:
                      type: number
                      format: float
                      nullable: false
                      example: 20.5937
                    long:
                      type: number
                      format: float
                      nullable: false
                      example: 78.9629
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: string
                        nullable: false
                        example: ABDM-1049
                      message:
                        type: string
                        nullable: false
                        example: Invalid Profile Share Intent Keys
                  - type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: string
                        nullable: false
                        example: ABDM-1025
                      message:
                        type: string
                        nullable: false
                        example: Invalid ServiceId
                  - type: object
                    required:
                      - code
                      - message
                    properties:
                      code:
                        type: string
                        nullable: false
                        example: ABDM-1050
                      message:
                        type: string
                        nullable: false
                        example: Invalid Profile Share Metadata Keys
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
  /v3/patient/profile/on-share:
    post:
      tags:
        - abdm-hiecm-profile-share
      operationId: profile-share 2
      summary: >-
        This API will be invoked by the HIP for sharing the response of HIECM's
        /api/v3/hiecm/profile/share API
      description: >-
        This is a API will be invoked by the <b>HIP</b> to share the response of
        HIECM's /api/v3/hiecm/profile/share API. <ol type='1'> <li>
        <b>Header</b>  <ol type='a'> <br/> <li>AUTHORIZATION will be provided by
        the gateway session API after the successful verification of client ID
        and Secret [ Example:
        eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ2YXNhbnRoYWt1bWFyLmtlc2F2 ]</li>
        <li>REQUEST_ID unique UUID[ Example:
        18235d89-cb13-479d-ad71-7a57d5f669a8 ]</li> <li>TIMESTAMP  actual time
        of the requested was initiated[ Example: 2022-10-06T10:10:00.587 ]</li>
        <li>X_CM_ID  consent manager ID[ Example: ABDM_SBX ]</li> </ol> </li>
        <br/> <li> <b>Request Body</b> <ol type='a'><br/> <li>acknowledgement is
        mandatory object in case of successful response</li> <li>error is
        optional object in case of successful response</li> <li>response is
        mandatory object in both the cases</li> </ol> </ol>
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/REQUEST_ID'
        - $ref: '#/components/parameters/TIMESTAMP'
        - $ref: '#/components/parameters/X_CM_ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required:
                    - response
                  properties:
                    acknowledgement:
                      type: object
                      nullable: false
                      required:
                        - abhaAddress
                        - status
                        - tokenNumber
                        - expiry
                      properties:
                        abhaAddress:
                          type: string
                          nullable: false
                          example: abc@abdm
                        status:
                          type: string
                          nullable: false
                          example: success
                        context:
                          type: string
                          nullable: false
                          example: 43
                        tokenNumber:
                          type: string
                          nullable: false
                          example: 3
                        expiry:
                          type: number
                          nullable: false
                          example: 180
                    response:
                      type: object
                      nullable: false
                      required:
                        - requestId
                      properties:
                        requestId:
                          type: string
                          format: uuid
                          nullable: false
                          example: 6f0b4665-a915-4c92-aa36-65afb4a2cd71
      responses:
        '200':
          description: OK
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
  /{callback_url}/v3/hip/patient/profile/share:
    post:
      servers:
       - url: https://integrator.callback.url
         description: Base path for operations with /v3/hip/patient/profile/share
      tags:
        - abdm-hip-profile-share
      operationId: profile-share 3
      summary: >-
        This API will be invoked by the HIP for sharing the response of HIECM's
        /api/v3/hiecm/profile/share API
      description: >-
        This is a API will be invoked by the <b>HIP</b> to share the response of
        HIECM's /api/v3/hiecm/profile/share API. <ol type='1'> <li>
        <b>Header</b>  <ol type='a'> <br/> <li>REQUEST_ID unique UUID[ Example:
        18235d89-cb13-479d-ad71-7a57d5f669a8 ]</li> <li>TIMESTAMP  actual time
        of the requested was initiated[ Example: 2022-10-06T10:10:00.587 ]</li>
        <li>X_HIP_ID  consent manager ID[ Example: ABDM_SBX ]</li> </ol> </li>
        <br/> <li> <b>Request Body</b> <ol type='a'><br/> <li>acknowledgement is
        mandatory object in case of successful response</li> <li>error is
        optional object in case of successful response</li> <li>response is
        mandatory object in both the cases</li> </ol> </ol>
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/REQUEST_ID'
        - $ref: '#/components/parameters/TIMESTAMP'
        - $ref: '#/components/parameters/X_HIP_ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - abhaAddress
                - kyc
                - intent
                - metaData
              properties:
                abhaAddress:
                  type: string
                  format: email
                  nullable: false
                  example: abc@abdm
                abhaNumber:
                  type: number
                  nullable: false
                  example: 12-3456-7890-1234
                name:
                  type: string
                  nullable: false
                  example: abdul kalam
                gender:
                  type: string
                  nullable: false
                  enum:
                    - D Do not want to disclose
                    - F Female
                    - M Male
                    - O Others
                  example: M - Male
                yearOfBirth:
                  type: integer
                  format: int32
                  nullable: false
                  example: 1931
                address:
                  type: string
                  nullable: false
                  example: Ramanathapuram, Tamil Nadu
                district:
                  type: string
                  nullable: false
                  example: Ramanathapuram
                state:
                  type: string
                  nullable: false
                  example: Tamil Nadu
                intent:
                  type: object
                  nullable: false
                  properties:
                    context:
                      type: number
                      nullable: false
                      example: 123
                    linkToken:
                      type: string
                      format: uuid
                      nullable: false
                      example: >-
                        eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ2YXNhbnRoYWt1bWFyLmtlc2F2
                metaData:
                  type: object
                  nullable: true
                  required:
                    - lat
                    - long
                  properties:
                    lat:
                      type: number
                      format: float
                      nullable: false
                      example: 20.5937
                    long:
                      type: number
                      format: float
                      nullable: false
                      example: 78.9629
      responses:
        '200':
          description: OK
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
  /v3/app/patient/profile/on-share:
    post:
      servers:
       - url: https://dev.abdm.gov.in/hiecm/api
         description: Base path for operations with /v3/app/patient/profile/on-share
      tags:
        - abdm-app-profile-share
      operationId: profile-share 4
      summary: >-
        This API will be invoked by the HIP for sharing the response of HIECM's
        /api/v3/hiecm/profile/share API
      description: >-
        This is a API will be invoked by the <b>HIP</b> to share the response of
        HIECM's /api/v3/hiecm/profile/share API. <ol type='1'> <li>
        <b>Header</b>  <ol type='a'> <br/> <li>Authorization will be provided by
        the gateway session API after the successful verification of client ID
        and Secret [ Example:
        eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJ2YXNhbnRoYWt1bWFyLmtlc2F2 ]</li>
        <li>REQUEST_ID unique UUID[ Example:
        18235d89-cb13-479d-ad71-7a57d5f669a8 ]</li> <li>TIMESTAMP  actual time
        of the requested was initiated[ Example: 2022-10-06T10:10:00.587 ]</li>
        <li>X_HIU_ID  HIU ID[ Example: ABDM_SBX ]</li> </ol> </li> <br/> <li>
        <b>Request Body</b> <ol type='a'><br/> <li>acknowledgement is mandatory
        object in case of successful response</li> <li>error is optional object
        in case of successful response</li> <li>response is mandatory object in
        both the cases</li> </ol> </ol>
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/REQUEST_ID'
        - $ref: '#/components/parameters/TIMESTAMP'
        - $ref: '#/components/parameters/X_HIU_ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - response
              properties:
                acknowledgement:
                  type: object
                  nullable: false
                  required:
                    - abhaAddress
                    - status
                    - tokenNumber
                    - expiry
                  properties:
                    abhaAddress:
                      type: string
                      nullable: false
                      example: abc@abdm
                    status:
                      type: string
                      nullable: false
                      example: success
                    context:
                      type: string
                      nullable: false
                      example: 43
                    tokenNumber:
                      type: string
                      nullable: false
                      example: 3
                    expiry:
                      type: number
                      nullable: false
                      example: 180
                response:
                  type: object
                  nullable: false
                  required:
                    - requestId
                  properties:
                    requestId:
                      type: string
                      format: uuid
                      nullable: false
                      example: 6f0b4665-a915-4c92-aa36-65afb4a2cd71
      responses:
        '200':
          description: OK
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable